version: '3'
services:
  driver:
    image: benkodaniel/rmdocker
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: host
    command: ros2 launch robomaster_ros main.launch model:=s1
  teleop:
    privileged: true
    image: benkodaniel/rmdocker
    network_mode: host
    command: ros2 launch robomaster_ros teleop.launch model:=s1
