controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    gim_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_controller:
      type: diff_drive_controller/DiffDriveController

gim_controller:
  ros__parameters:
    joints:
      - gimbal_joint
      - blaster_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50

diff_controller:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names:
      - front_left_wheel_joint
    right_wheel_names:
      - front_right_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    wheel_separation: 0.25
    wheel_radius: 0.05
    use_stamped_vel: false