# PS4 wireless controller
# Deadman (enable) button: R1

# Buttons on PS4
    #  Square  = joystick button 0
    #  X       = joystick button 1
    #  Circle  = joystick button 2
    #  Triangle= joystick button 3
    #  L1      = joystick button 4
    #  R1      = joystick button 5
    #  L2      = joystick button 6
    #  R2      = joystick button 7
    #  Share	= joystick button 8
    #  Options = joystick button 9
    #  L3      = joystick button 10
    #  R3      = joystick button 11
    #  PS      = joystick button 12
    #  PadPress= joystick button 13

#  Axes:
#      LeftStickX      = X-Axis
#      LeftStickY      = Y-Axis (Inverted?)
#      RightStickX     = 3rd Axis
#      RightStickY     = 4th Axis (Inverted?)
#      L2              = 5th Axis (-1.0f to 1.0f range, unpressed is -1.0f)
#      R2              = 6th Axis (-1.0f to 1.0f range, unpressed is -1.0f)
#      DPadX           = 7th Axis
#      DPadY           = 8th Axis (Inverted?)



/**:
  ros__parameters:
    piloting:
      type: topic
      interface_type: "geometry_msgs/msg/Twist"
      topic_name: cmd_vel
      #deadman_buttons: [5]  # RT R1 + bal joy
      axis_mappings:
        linear-x:
          axis: 0  #vizszintes
          scale: 1.5
          offset: 0
        linear-y:
          axis: 1   #fuggoleges
          scale: 1.5
          offset: 0 #/1.5?
        #angular-z:   #felesleges, ugyse repul
          #axis: 0
          #scale: 3
          #offset: 0
    gimbal:
      type: topic
      interface_type: "robomaster_msgs/msg/GimbalCommand"
      topic_name: cmd_gimbal
      #deadman_buttons: [6]  # RT L1+jobb joy
      axis_mappings:
        yaw_speed:
          axis: 3    #vizszintes
          scale: -3
          offset: 0
        pitch_speed:
          axis: 4   #fuggoleges
          scale: -3
          offset: 0
    yellow:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [7, 3]  # RT R2+haromszog
      message_value:
        color-r:
          value: 1.0
        color-g:
          value: 1.0
    blue:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [7, 0]  # RT R2+ negyszog
      message_value:
        color-b:
          value: 1.0
    green:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [7, 1]  # RT R2+X
      message_value:
        color-g:
          value: 1.0
    black:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [7, 5]  # RT R2+R1
      message_value:
        color-g:
          value: 0.0
    red:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [7, 2]  # RT R2+ kor
      message_value:
        color-r:
          value: 1.0
    blaster-on:
      type: topic
      interface_type: "robomaster_msgs/msg/BlasterLED"
      topic_name: blaster_led
      deadman_buttons: [6, 1]  # RT L2+X
      message_value:
        brightness:
          value: 1.0
    blaster-off:
      type: topic
      interface_type: "robomaster_msgs/msg/BlasterLED"
      topic_name: blaster_led
      deadman_buttons: [6, 0]  # RT L2+negyszog
      message_value:
        brightness:
          value: 0.0
    mode-chassis:
      type: topic
      interface_type: "robomaster_msgs/msg/Mode"
      topic_name: mode
      deadman_buttons: [7]  # RT  R2
      message_value:
        mode:
          value: 2
    lock-gimbal:
      type: topic
      interface_type: "std_msgs/msg/Bool"
      topic_name: lock
      deadman_buttons: [7, 5]  # RT   R2+R1
      message_value:
        data:
          value: true
    mode-free:
      type: topic
      interface_type: "robomaster_msgs/msg/Mode"
      topic_name: mode
      deadman_buttons: [4]  # RT L1
      message_value:
        mode:
          value: 0
    recenter:
      type: action
      interface_type: robomaster_msgs/action/RecenterGimbal
      action_name: recenter_gimbal
      buttons: [8]    #share
