name: Robomaster Docker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/benkodaniel/robomaster:latest .

      - name: Test Docker image
        run: |
          docker run --rm \
            --env DISPLAY=:0 \
            --env LIBGL_ALWAYS_SOFTWARE=1 \
            ghcr.io/benkodaniel/robomaster:latest \
            bash -c "source /opt/ros/humble/setup.bash && ros2 node list"

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/benkodaniel/robomaster:latest
